default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://postgres@127.0.0.1:55432/pushpet_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://postgres@127.0.0.1:55432/pushpet_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
